### ISSUE TITLE
Please make this plugin available on opam

### ISSUE THREAD

**Issue by JasonGross** [herbelin/reduction-effects#1]
Despite the claim to ["eventually submit as an opam package"](https://github.com/coq/coq/pull/714#issuecomment-307359498) a year and a half ago, I cannot find it [on opam](https://github.com/coq/opam-coq-archive/search?q=reduction-effects&unscoped_q=reduction-effects).  I think it is worth submitting now (and keeping up to date, and maybe adding to the CI?), even if it does not yet have the additional features you mentioned in that comment.

**Comment by liyishuai** [comment]
An OPAM release is ready, provided coq-community/manifesto#51 gets resolved.
Update: release proposed in coq/opam-coq-archive#622.
